# Generated by Django 5.1.5 on 2025-01-29 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Mens Clothing', 'Mens Clothing'), ('Women Clothing', 'Women Clothing'), ('Footwaer', 'Footwaer'), ('Accessories', 'Accessories '), ('Grooming Products', 'Grooming Products')], max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('gender', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
